changed annotation procedure
removed annotation of bed to have only pivot, annotation of pivot intorduced, changed way to calculate deltap, deltaq, deltarp and deltrq,
added cmd check actions to test

diff --git a/.github/workflows/all-actions.yaml b/.github/workflows/all-actions.yaml
--- a/.github/workflows/all-actions.yaml
+++ b/.github/workflows/all-actions.yaml
@@ -1,37 +1,37 @@
-name: Combined R Workflow
-
-on:
-  push:
-    branches: [main, master, develop]
-  pull_request:
-    branches: [main, master]
-  release:
-    types: [published]
-  workflow_dispatch:
-
-jobs:
-  prepare:
-    runs-on: ubuntu-latest
-    outputs:
-      r-version: ${{ steps.setup-r.outputs.r-version }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Set up Pandoc
-        uses: r-lib/actions/setup-pandoc@v2
-
-      - name: Set up R
-        id: setup-r
-        uses: r-lib/actions/setup-r@v2
-        with:
-          use-public-rspm: true
-
-      - name: Install common dependencies
-        uses: r-lib/actions/setup-r-dependencies@v2
-        with:
-          extra-packages: any::rcmdcheck, any::pkgdown, any::covr, any::rmarkdown
-          needs: release-create, website, coverage
+# name: Combined R Workflow
+#
+# on:
+#   push:
+#     branches: [main, master, develop]
+#   pull_request:
+#     branches: [main, master]
+#   release:
+#     types: [published]
+#   workflow_dispatch:
+#
+# jobs:
+#   prepare:
+#     runs-on: ubuntu-latest
+#     outputs:
+#       r-version: ${{ steps.setup-r.outputs.r-version }}
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
+#
+#       - name: Set up Pandoc
+#         uses: r-lib/actions/setup-pandoc@v2
+#
+#       - name: Set up R
+#         id: setup-r
+#         uses: r-lib/actions/setup-r@v2
+#         with:
+#           use-public-rspm: true
+#
+#       - name: Install common dependencies
+#         uses: r-lib/actions/setup-r-dependencies@v2
+#         with:
+#           extra-packages: any::rcmdcheck, any::pkgdown, any::covr, any::rmarkdown
+#           needs: release-create, website, coverage
 
   # R-CMD-check:
   #   runs-on: ${{ matrix.config.os }}
@@ -61,100 +61,100 @@ jobs:
   #       with:
   #         upload-snapshots: true
 
-  pkgdown:
-    runs-on: ubuntu-latest
-    needs: prepare
-    concurrency:
-      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-    steps:
-      # - name: Checkout repository
-      #   uses: actions/checkout@v4
+  # pkgdown:
+  #   runs-on: ubuntu-latest
+  #   needs: prepare
+  #   concurrency:
+  #     group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #   steps:
+  #     # - name: Checkout repository
+  #     #   uses: actions/checkout@v4
+  #
+  #     - name: Build site
+  #       run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
+  #       shell: Rscript {0}
+  #
+  #     - name: Deploy to GitHub Pages 🚀
+  #       if: github.event_name != 'pull_request'
+  #       uses: JamesIves/github-pages-deploy-action@v4.4.1
+  #       with:
+  #         clean: false
+  #         branch: gh-pages
+  #         folder: docs
 
-      - name: Build site
-        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
-        shell: Rscript {0}
+  # release-create:
+  #   runs-on: ubuntu-latest
+  #   needs: prepare
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #     R_KEEP_PKG_SOURCE: yes
+  #   steps:
+  #     - name: Build package
+  #       run: |
+  #         R CMD build .
+  #
+  #     - name: Create Release
+  #       uses: softprops/action-gh-release@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Deploy to GitHub Pages 🚀
-        if: github.event_name != 'pull_request'
-        uses: JamesIves/github-pages-deploy-action@v4.4.1
-        with:
-          clean: false
-          branch: gh-pages
-          folder: docs
+  # test-coverage:
+  #   runs-on: ubuntu-latest
+  #   needs: prepare
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #   steps:
+  #     # - name: Checkout repository
+  #     #   uses: actions/checkout@v4
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
+  #
+  #     - name: Set up R
+  #       uses: r-lib/actions/setup-r@v2
+  #       with:
+  #         r-version: '4.4.0' # Specify the R version you need
+  #
+  #     - name: Run test coverage
+  #       run: |
+  #         covr::codecov(
+  #           quiet = FALSE,
+  #           clean = FALSE,
+  #           install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
+  #         )
+  #       shell: Rscript {0}
+  #
+  #     - name: Display testthat output
+  #       if: always()
+  #       run: |
+  #         find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+  #       shell: bash
+  #
+  #     - name: Upload test results
+  #       if: failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: coverage-test-failures
+  #         path: ${{ runner.temp }}/package
 
-  release-create:
-    runs-on: ubuntu-latest
-    needs: prepare
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      R_KEEP_PKG_SOURCE: yes
-    steps:
-      - name: Build package
-        run: |
-          R CMD build .
-
-      - name: Create Release
-        uses: softprops/action-gh-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  test-coverage:
-    runs-on: ubuntu-latest
-    needs: prepare
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-    steps:
-      # - name: Checkout repository
-      #   uses: actions/checkout@v4
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up R
-        uses: r-lib/actions/setup-r@v2
-        with:
-          r-version: '4.4.0' # Specify the R version you need
-
-      - name: Run test coverage
-        run: |
-          covr::codecov(
-            quiet = FALSE,
-            clean = FALSE,
-            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
-          )
-        shell: Rscript {0}
-
-      - name: Display testthat output
-        if: always()
-        run: |
-          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
-
-      - name: Upload test results
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-test-failures
-          path: ${{ runner.temp }}/package
-
-  render-rmarkdown:
-    runs-on: ubuntu-latest
-    needs: prepare
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-    steps:
-      # - name: Checkout repository
-      #   uses: actions/checkout@v4
-      #   with:
-      #     fetch-depth: 0
-
-      - name: Render Rmarkdown files and Commit Results
-        run: |
-          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
-          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
-          git config --local user.name "$GITHUB_ACTOR"
-          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
-          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
-          git push origin || echo "No changes to commit"
+  # render-rmarkdown:
+  #   runs-on: ubuntu-latest
+  #   needs: prepare
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #   steps:
+  #     # - name: Checkout repository
+  #     #   uses: actions/checkout@v4
+  #     #   with:
+  #     #     fetch-depth: 0
+  #
+  #     - name: Render Rmarkdown files and Commit Results
+  #       run: |
+  #         RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+  #         Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+  #         git config --local user.name "$GITHUB_ACTOR"
+  #         git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+  #         git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
+  #         git push origin || echo "No changes to commit"
 
